Same casing problems for credentials too.
Inconsistent casing cause errors on install: Error loading package "n8n-nodes-transcribe-com" :The specified package could not be loaded
ResponseError: Error loading package "n8n-nodes-transcribe-com" :The specified package could not be loaded
    at CommunityPackagesController.installPackage (/Users/ipv6/.nvm/versions/node/v22.22.0/lib/node_modules/n8n/src/modules/community-packages/community-packages.controller.ts:132:10)
    at handler (/Users/ipv6/.nvm/versions/node/v22.22.0/lib/node_modules/n8n/src/controller.registry.ts:110:12)
    at /Users/ipv6/.nvm/versions/node/v22.22.0/lib/node_modules/n8n/src/response-helper.ts:161:17